language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

  - cd udagram-backend-feed
  - docker build -t udagram-feed-api .
  - docker tag udagram-feed-api $DOCKER_USERNAME/udagram-feed-api:latest

  - cd ../udagram-backend-user
  - docker build -t udagram-user-api .
  - docker tag udagram-user-api $DOCKER_USERNAME/udagram-user-api:latest

  - cd ../udagram-frontend
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:latest

  - cd ../udagram-deployment
  - docker build -t udagram-reverse-proxy .
  - docker tag udagram-reverse-proxy $DOCKER_USERNAME/udagram-reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/udagram-feed-api
  - docker push $DOCKER_USERNAME/udagram-user-api
  - docker push $DOCKER_USERNAME/udagram-frontend
  - docker push $DOCKER_USERNAME/udagram-reverse-proxy
